// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_mem_lee = "CgkI47GpjtgUEAIQBw"; // <GPGSID>
        public const string achievement_i_believe_i_can_fly = "CgkI47GpjtgUEAIQBQ"; // <GPGSID>
        public const string leaderboard_highscore = "CgkI47GpjtgUEAIQAQ"; // <GPGSID>
        public const string achievement_concrete_jungle = "CgkI47GpjtgUEAIQCg"; // <GPGSID>
        public const string achievement_death_is_your_friend = "CgkI47GpjtgUEAIQBg"; // <GPGSID>
        public const string achievement_out_of_the_woods = "CgkI47GpjtgUEAIQCQ"; // <GPGSID>
        public const string achievement_i_am_hell_incarnate = "CgkI47GpjtgUEAIQDA"; // <GPGSID>
        public const string achievement_cheater = "CgkI47GpjtgUEAIQBA"; // <GPGSID>
        public const string achievement_god_mode = "CgkI47GpjtgUEAIQAg"; // <GPGSID>
        public const string achievement_onto_the_fire = "CgkI47GpjtgUEAIQCw"; // <GPGSID>
        public const string achievement_theatre_connoisseur = "CgkI47GpjtgUEAIQCA"; // <GPGSID>
        public const string achievement_playing_it_safe = "CgkI47GpjtgUEAIQAw"; // <GPGSID>
        public const string achievement_who_needs_double_jump_anyways = "CgkI47GpjtgUEAIQDQ"; // <GPGSID>

}

